env:
  global:
  - CONAN_TOTAL_PAGES: 8
linux:
  os: linux
  sudo: required
  language: python
  python: '3.6'
  services: &1
  - docker
osx:
  os: osx
  language: generic
matrix:
  include:
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=5
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=6
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=7
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=8
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=5
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=6
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=5
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=6
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=5
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=6
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=5
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=6
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=5
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=6
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=1
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=2
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=3
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=4
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=1
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=2
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=3
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=4
  - os: osx
    language: generic
    osx_image: xcode9.2
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=1
  - os: osx
    language: generic
    osx_image: xcode9.2
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=2
  - os: osx
    language: generic
    osx_image: xcode9.2
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=3
  - os: osx
    language: generic
    osx_image: xcode9.2
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=4
install:
- chmod +x .travis/install.sh
- "./.travis/install.sh"
script:
- chmod +x .travis/run.sh
- "./.travis/run.sh"

deploy:
  provider: bintray
  user: lucienboillod
  key:
    secure: jyatjkww3cgasBfrQKQoYDPUala4v4mD70FqR8zasuvpVn20Urf0YDWwhqXZSMYVQA03Wu8PZV9vwA9xjBmqRWLyAjMucpVcMaHIHyHQmM3QcG6GdWuZYvbC4CipWj5XTI72VW11KKaLQ+xCAJrGcrHjrrKfCMq3FWRY0YDGUCzfih6MF/mTPgyNgUZ12xrqi682BZd6xM5KfiM+3JuHeNbJ46yqZSjemOhX17eye8mmoHCyVUN1r+HLZTup8pNSp7jAyv3m2rvl/pOU5W6ISVGsMsIIMoirvk58zM+O5ncj2RUybA42Yzp8khCP4Rs3+umSP517/M8mmdEg7UrZ82/THufqg1vL6vM/6CVKg+Xt1y5/DaFpfFbRtPx/lWYdCgUxQ5Hq6hXX4wl2b9j04RCOC63+o7qGMOG43eaiGyRx2HasAo7gpE8HqJ0qPiVSAsxNeQJINUvtyFP9t6pD+j3JLyzs7JEymZNOVdLgdpkGl4D1vVdkxolcnEVmPQNihGxdCkU5ytBuASgMiJX6TOHBwgPEL3su77XEl73g2R/9RPmRMd7j2+EX8pREjeWjRTNqvfixbNSJyjswKwolsx8ImNF67e1zFsW/4torhi+vtQkz8zQqLQMBKEcLeGipNJG4eoLq/dPileXUxNUzBcm5+UlCAkjEkqYG2LB0VWM=
  skip_cleanup: true